GET http://localhost:8000/transaction/9b11bbdb874a4a3dab918da0a43ffa16
Accept: application/json

###
### use balance
POST http://localhost:8000/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 100000
}
###
### cancel balance
POST http://localhost:8000/transaction/cancel
Content-Type: application/json

{
  "transactionId": "c23ac77a9f234006acd5f4fa69ee80d6",
  "accountNumber": "1000000001",
  "amount": 200000
}
###